### PR TITLE
PowerShell rewrite

### PR DESCRIPTION
**Pull request by StuckDuck7710**
## Changes
- Switched to PowerShell instead of Batch
- Refactored and cleaned code
- Added one click installe
- Added the £ command

### CODE REVIEW

**Comment by StuckDuck7710** [comment]
fra 😐 pls

**Comment by franzageek** [comment]
cos

**Comment by StuckDuck7710** [comment]
Thx 💙

**Comment by franzageek** [comment]
np

**Comment by franzageek** [comment]
np bro😉

**Pull request merged**
